Repository cloudmesh-community/book, pull requests merged in 2019-02, with the labels that each got.

#361 Chapter: AWS Document DB.md
  chapters/in/AWS Document DB.md
Labels: assigned, chapter

#346 Numpy Section Rewrite
  chapters/prg/python/numpy/numpy.md
Labels: help wanted

#389 Added images and sections for data exploration in machine learning
  chapters/prg/python/scikit-learn/images/scikit-learn-barplot.png
  chapters/prg/python/scikit-learn/images/scikit-learn-boxplot.png
  chapters/prg/python/scikit-learn/images/scikit-learn-correlationanalysis.png
  chapters/prg/python/scikit-learn/images/scikit-learn-histograms.png
  chapters/prg/python/scikit-learn/images/scikit-learn-scatterplot.png
  chapters/prg/python/scikit-learn/scikit-learn.md
Labels: bug
